### ISSUE TITLE
Why can't I access your website? I either get a 404 error or am redirected to another site. Please look into this issue.

### ISSUE THREAD

**Issue by xigua314** [mlc-ai/xgrammar#114]
Why can't I access your website? I either get a 404 error or am redirected to another site. Please look into this issue.

**Comment by Ubospica** [comment]
Hi @xigua314, which website are you accessing? I can access https://xgrammar.mlc.ai/ and https://xgrammar.mlc.ai/docs/ in the US. As these pages are hosted on the Github pages, they may not be accessible in certain places like China due to GFW.

**Comment by xigua314** [comment]
Thanks for your reply. it's working now

Yixin Dong ***@***.***> 于2024年12月4日周三 16:35写道：
