### ISSUE TITLE
Pydantic list cannot be empty? 

### ISSUE THREAD

**Issue by arunpatala** [mlc-ai/xgrammar#135]
```
class Profile(BaseModel):
    languages: List[str]
```
    
 Suppose I have a documents and I want to extract list of languages specified in it. I define it as above. The list can potentially be empty when there are no languages in the document. Then expected output is a empty list. Using json schema of xgrammar, the list is always non empty. Without schema generation, the same llm is outputting empty list as expected. 

Is this the expected behaviour, or should i use something as follows, which also didnt help
```
class Profile(BaseModel):
    languages: Optional[List[str]] = None
```
    
 
 Does this have anything to do with whitespace formatting? I tried checking with and without it and it didnt help.
 
 I am using llama 3.1 8B instruct with VLLM latest docker image with vllm=v0.6.5 and xgrammar >= 0.1.6;

**Comment by Ubospica** [comment]
That is a current restriction to enhance the output quality because sometimes llm output an empty array when it shouldn't. Currently you can set `strict_mode=False` when compiling json schema to allow empty arrays. Considering the requirement for empty arrays, we are considering removing this restriction in the next version.

**Comment by arunpatala** [comment]
thanks for the reply. i will try with strict_mode=False.

**Comment by arunpatala** [comment]
How do i use this mode in VLLM, do we set the argument when starting the engine ? or do we set the argument when sending the request?

currently i am using open ai API to pass the class and dont seem to have a particular way to set the strict_mode=False

```
completion = self.client.beta.chat.completions.parse(
                     model=self.model,
                      messages=messages,
                      response_format=pydantic_class,
                      **sampling_params
                    )
```

appreciate your help.

**Comment by khongtrunght** [comment]
How to use strict_mode=False in VLLM @arunpatala . I need your help.

**Comment by Ubospica** [comment]
> How to use strict_mode=False in VLLM @arunpatala . I need your help.

We will communicate with the vLLM team on this. It could be possible if we can pass some extra args in the request args.
